### ISSUE TITLE
login functionality failure

### ISSUE THREAD

**Issue by fanindraHIRAPURE** [Him104/project-1#2]
After creating new author successfully user is failed to login using valid email and password.
status code= 500 

author created successfully -
![Screenshot 2023-11-17 221131](https://github.com/Him104/project-1/assets/119760892/620320b3-6176-432c-b95f-5fc2917e599b)

login failure-
![Screenshot 2023-11-17 220622](https://github.com/Him104/project-1/assets/119760892/0439da76-2c95-4039-b320-e17b1251236f)

**Comment by Him104** [comment]
issue is fixed, try now.... @fanindraHIRAPURE
